### ISSUE TITLE
updateFromJS using

### ISSUE THREAD

**Issue by Helen1987** [arj03/knockout.wrap#12]
I wanted to use ko.wrap.updateFromJS in following way:
`ko.wrap.updateFromJS (newNode, options, mappingData);`
where `mappingData` is data which I have to map to existing `newNode` object of my custom class. I was not able to to it, as for some reason `updateFromJS` expect that `newNode` is observable. It's not true in my case.
How can I overcome this trouble?

**Comment by arj03** [comment]
If it isn't an observable what should it then do? 

The purpose of the function is update an _observable_ with som js data.

**Comment by Helen1987** [comment]
In short, I have an original object with a lot of observable properties. I want to update the value of those properties with values of new object and add new properties from new object if they were not present in original one.

**Comment by arj03** [comment]
A pull request with added tests would be welcome.
